# Generated by Django 2.2 on 2019-04-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
    ]
